import os
import sqlite3
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

ROOT = Path(__file__).resolve().parent.parent
DB_PATH = Path(__file__).resolve().parent / 'todos.db'
DATABASE_URL = os.getenv('DATABASE_URL')


class Database:
    """Use SQLite locally and Postgres for persistent Vercel storage."""

    def __init__(self):
        self.postgres = bool(DATABASE_URL)
        if self.postgres:
            import psycopg
            from psycopg.rows import dict_row

            self.connection = psycopg.connect(DATABASE_URL, row_factory=dict_row)
        elif os.getenv('VERCEL'):
            raise RuntimeError('Add the Neon connection as the DATABASE_URL environment variable in Vercel.')
        else:
            self.connection = sqlite3.connect(DB_PATH)
            self.connection.row_factory = sqlite3.Row

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        if self.postgres:
            self.connection.__exit__(exc_type, exc_value, traceback)
        else:
            try:
                self.connection.__exit__(exc_type, exc_value, traceback)
            finally:
                self.connection.close()

    def execute(self, query, parameters=()):
        if self.postgres:
            query = query.replace('?', '%s')
        return self.connection.execute(query, parameters)

    def executemany(self, query, parameters):
        if self.postgres:
            query = query.replace('?', '%s')
        return self.connection.executemany(query, parameters)


def connect():
    return Database()


def initialize_database():
    if DATABASE_URL:
        statement = 'CREATE TABLE IF NOT EXISTS todos (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, text TEXT NOT NULL, done BOOLEAN NOT NULL DEFAULT FALSE, position INTEGER NOT NULL)'
    else:
        statement = 'CREATE TABLE IF NOT EXISTS todos (id INTEGER PRIMARY KEY AUTOINCREMENT, text TEXT NOT NULL, done INTEGER NOT NULL DEFAULT 0, position INTEGER NOT NULL)'
    with connect() as db:
        db.execute(statement)


app = FastAPI(title='Little List API')
app.add_middleware(
    CORSMiddleware,
    allow_origins=['http://localhost:5173', 'http://127.0.0.1:5173'],
    allow_methods=['*'],
    allow_headers=['*'],
)

if not os.getenv('VERCEL') or DATABASE_URL:
    initialize_database()


class NewTodo(BaseModel):
    text: str


class TodoUpdate(BaseModel):
    done: bool


class Reorder(BaseModel):
    ids: list[int]


def convert(row):
    return {'id': row['id'], 'text': row['text'], 'done': bool(row['done']), 'position': row['position']}


def database_error():
    raise HTTPException(503, 'Online storage is not connected yet. Add DATABASE_URL in the Vercel project settings.')


@app.get('/api/todos')
def list_todos():
    try:
        with connect() as db:
            return [convert(row) for row in db.execute('SELECT * FROM todos ORDER BY position, id').fetchall()]
    except RuntimeError:
        database_error()


@app.post('/api/todos', status_code=201)
def add_todo(item: NewTodo):
    text = item.text.strip()
    if not text:
        raise HTTPException(400, 'Please enter a task.')
    try:
        with connect() as db:
            position = db.execute('SELECT COALESCE(MAX(position), -1) + 1 AS next_position FROM todos').fetchone()['next_position']
            row = db.execute('INSERT INTO todos (text, position) VALUES (?, ?) RETURNING *', (text, position)).fetchone()
            return convert(row)
    except RuntimeError:
        database_error()


@app.patch('/api/todos/{todo_id}')
def update_todo(todo_id: int, item: TodoUpdate):
    try:
        with connect() as db:
            cursor = db.execute('UPDATE todos SET done = ? WHERE id = ?', (item.done, todo_id))
            if not cursor.rowcount:
                raise HTTPException(404, 'Task not found.')
            return convert(db.execute('SELECT * FROM todos WHERE id = ?', (todo_id,)).fetchone())
    except RuntimeError:
        database_error()


@app.delete('/api/todos/{todo_id}', status_code=204)
def delete_todo(todo_id: int):
    try:
        with connect() as db:
            if not db.execute('DELETE FROM todos WHERE id = ?', (todo_id,)).rowcount:
                raise HTTPException(404, 'Task not found.')
    except RuntimeError:
        database_error()


@app.put('/api/todos/order')
def reorder_todos(order: Reorder):
    try:
        with connect() as db:
            existing = {row['id'] for row in db.execute('SELECT id FROM todos')}
            if len(order.ids) != len(existing) or set(order.ids) != existing:
                raise HTTPException(400, 'Order must include every task exactly once.')
            db.executemany('UPDATE todos SET position = ? WHERE id = ?', [(i, todo_id) for i, todo_id in enumerate(order.ids)])
        return {'ok': True}
    except RuntimeError:
        database_error()


if os.getenv('VERCEL'):
    app.frontend('/', directory=ROOT / 'frontend' / 'dist')
